GPT4ALL_MODEL_NAME='llama-2-7b-chat.Q4_0.gguf' 

GPT4ALL_MODEL_FOLDER_PATH='C:/Users/andre/AppData/Local/nomic.ai/GPT4All/'
GPT4ALL_BACKEND='llama'
GPT4ALL_ALLOW_STREAMING=True
GPT4ALL_ALLOW_DOWNLOAD=False