# GPT4ALL_MODEL_NAME='llama-2-7b-chat.Q4_0.gguf' 
GPT4ALL_MODEL_NAME='mistral-7b-openorca.gguf2.Q4_0.gguf' 

GPT4ALL_MODEL_FOLDER_PATH='./models'
GPT4ALL_BACKEND='llama'
GPT4ALL_ALLOW_STREAMING=True
GPT4ALL_ALLOW_DOWNLOAD=True